### ISSUE TITLE
Result Display [2023/06/20]

### ISSUE THREAD

**Issue by Quentin-Clement** [algosup/2022-2023-project-5-algorithmics-Team-7#11]
### Description

What is displayed in the command line should be put in a log file but not directly displayed in the command line.

### Severity

4 - Low

### Version

https://github.com/cdiggins/wine-mixer/releases/tag/june-16

### System informations

Platform: Any (Mac)
Mono version: Any (6.12.0)

### Steps taken

Run the program.

### Expected result

Just a sentence such as:
- "The program is finished" if it ran correctly.
- An error message specifying the error that occurred.
Nothing more should be in the command line, all the others information should be in a log file.

**Comment by cdiggins** [comment]
No time to fix this.

**Comment by cdiggins** [comment]
By the way: can't you just redirect the output to a file using shell commands?
