### ISSUE TITLE
Functional-Specifications.md correction

### ISSUE THREAD

**Issue by Quentin-Clement** [algosup/2022-2023-project-5-algorithmics-Team-7#2]
The [Functional Specifications](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/blob/main/Documents/Functional-Specifications.md) need to be corrected on some points. These points are detailed in a dedicated [test case](https://docs.google.com/spreadsheets/d/1uCJrfU7ePSEYzvzTxc2P3sQFFSlSrLOx6Xyt8DMNn74/edit?usp=sharing) and need to be changed as soon as possible.

**Comment by KarineVinette** [comment]
I have corrected the points that you made clear.
