### ISSUE TITLE
One wine, one tank [2023/05/25]

### ISSUE THREAD

**Issue by Quentin-Clement** [algosup/2022-2023-project-5-algorithmics-Team-7#5]
### Description

When you input one wine and one tank, it returns an error. Instead, it should return an empty output/steps.txt file.

### Severity

2 - High

### System informations

Platform: Windows
Mono version: dotnet 6.0.408

### Steps taken

Change the inputs:
input/recipe.txt:
100

input/tanks.txt:
10

Command line: WineMixer.exe input/tanks.txt input/recipe.txt

### Expected result

output/result.txt:
100.000

output/steps.txt:

### Other

[error.md](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/files/11552837/error.md)

**Comment by leo-chartier** [comment]
Fixed by version 2023/05/30.
