### ISSUE TITLE
Output folder on mac [2023/05/31]

### ISSUE THREAD

**Issue by leo-chartier** [algosup/2022-2023-project-5-algorithmics-Team-7#6]
### Description

The program tries to write the output files in the `/usr/local/share/dotnet/output` folder.
Note: since it is a protected folder, you need to run the program with sudo.

### Severity

4 - Low

### Version

2023/05/30

### System informations

Platform: Mac
Mono version: 6.12.0.182

### Steps taken

Run the program with any valid inputs.
`dotnet WineMixer.dll input/tanks.txt input/recipe.txt`

### Expected result

Output the files in an `output` folder on the same level as the program.

### Workaround or solution

Edit the configuration file to use an absolute path temporarily solves the issue.

**Comment by cdiggins** [comment]
I'm not going to fix this one. Only occurs on Mac, and there are two workarounds: run as sudo, or specify a different output folder.
