### ISSUE TITLE
Output .json [2023/06/12]

### ISSUE THREAD

**Issue by Quentin-Clement** [algosup/2022-2023-project-5-algorithmics-Team-7#7]
### Description

Each time the program has processed, an output file is created named output-2023-XX-XX-XX-XX-XX.json. The file is empty and should either not be created or be filled with something relevant such as logs.

### Severity

4 - Low

### Version

2023/05/30

### System informations

Platform: Mac
Mono version: 6.12.0.182

### Steps taken

Run the program with any valid inputs.
`dotnet WineMixer.dll input/tanks.txt input/recipe.txt`

### Expected result

It must not have an empty .json file.

**Comment by cdiggins** [comment]
Decided not to create the JSON file: it was too big (20MB for medium sized test data).

**Comment by cdiggins** [comment]
Should be fixed in new release: https://github.com/cdiggins/wine-mixer/releases/tag/june-14

**Comment by leo-chartier** [comment]
The file is indeed not being created anymore. Closing the issue now.
