### ISSUE TITLE
Wrong final blend for simple example [2023/06/15]

### ISSUE THREAD

**Issue by leo-chartier** [algosup/2022-2023-project-5-algorithmics-Team-7#8]
### Description

The given blend is worse than the one found by hand.

### Severity

2 - High

### Version

june-14

### System informations

Platform: Any (Mac)
Mono version: Any (6.12.0.182)

### Steps taken

Input files:
[recipe.txt](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/files/11759504/recipe.txt)
[tanks.txt](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/files/11759507/tanks.txt)

### Expected result

Expected steps:
(2) -> (3, 4)
(0, 1) -> (2)
(2 -> 0) + (2, 4) -> (5)

Expected formula:
19
38
43

Actual results:
[steps.txt](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/files/11759628/steps.txt)
[result.txt](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/files/11759627/result.txt)

### Other

Log file:
[log.txt](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/files/11759682/log.txt)

**Comment by cdiggins** [comment]
I don't understand the last step: 
(2 -> 0) + (2, 4) -> (5)
Can you explain? 
Normally it is just "left inputs" and "right outputs" (e.g. (a, b, c) -> (d, e, f))
The algorithm only considers transitions from occupied input tanks to unoccupied output tanks.

**Comment by leo-chartier** [comment]
It is the example we used in the functional specifications.
![graph](https://github.com/algosup/2022-2023-project-5-algorithmics-Team-7/assets/91249751/204689a7-5337-4f8d-a896-07b238fd1fa6)

**Comment by cdiggins** [comment]
Unfortunately the algorithm doesn't consider these kinds of cases: each transfer is a set of inputs mixed, to one or more outputs. This kind of hybrid approach (partially splitting a tank so that it goes into two sets of outputs). Would be massively more complicated to code. 

We won't be able to fix this in time.
